name: Merge on Command

on:
  issue_comment:
    types: [created]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'PLEASE MERGE')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Merge Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        python -c "import requests; import os; api_url = f'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}/merge'; headers = {'Authorization': f'token {os.getenv('GITHUB_TOKEN')}', 'Accept': 'application/vnd.github.v3+json'}; data = {'commit_title': f'Automatically merging PR #${{ github.event.issue.number }}', 'merge_method': 'merge'}; response = requests.put(api_url, headers=headers, json=data); print('Response:', response.status_code, response.text);"
      
      shell: bash